# Intro to Numpy

In [1]:
# importing numpy

import numpy as np

In [2]:
# declaring an array
np.array([1,3,5,7])


array([1, 3, 5, 7])

In [5]:
A = np.mat([[1,2],[3,4]])
A

matrix([[1, 2],
        [3, 4]])

## Matrix Operations

In [9]:
#
print(A+A)
print()
print(A-A)
print()
print(A*A)

[[2 4]
 [6 8]]

[[0 0]
 [0 0]]

[[ 7 10]
 [15 22]]


## Matrix Determinant

In [10]:
#Finding out the determinant of the matrix

np.linalg.det(A)

-2.0000000000000004

## Matrix Transpose

In [12]:
print(A)
print(np.matrix.transpose(A))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [13]:
A = np.mat([[1,2,3],[4,5,6],[7,8,9]])